### ISSUE TITLE
error duriung parsing sparql command line arguments

### ISSUE THREAD

**Issue by jgrzebyta** [jgrzebyta/triple-loader#10]
Error during parsing sparql command line arguments:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Data files and types are not matched {:causes #{:data-files-and-types-not-matched}, :length {:data 1, :types 2}}
    at clojure.core$ex_info.invokeStatic(core.clj:4617)
    at clojure.core$ex_info.invoke(core.clj:4617)
    at sparql$map_seqs.invokeStatic(sparql.clj:40)
    at sparql$map_seqs.invoke(sparql.clj:33)
    at sparql$_main.invokeStatic(sparql.clj:63)
    at sparql$_main.doInvoke(sparql.clj:46)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at sparql.main(Unknown Source)
```

**Comment by jgrzebyta** [comment]
Fixed in a516a2182db2f5e135f3e9cdc91fb894646fb7f2.
