### ISSUE TITLE
Error: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions

### ISSUE THREAD

**Issue by jgrzebyta** [jgrzebyta/triple-loader#16]
Error occurs on Mac 

```


Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentList

Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentList


```

**Comment by jgrzebyta** [comment]
Confirmed on Linux.

stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentList
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
	at clojure.java.io$fn__9390$G__9372__9395.invoke(io.clj:35)
	at clojure.java.io$file.invokeStatic(io.clj:424)
	at clojure.java.io$file.invoke(io.clj:418)
	at triple.loader$do_loading.invokeStatic(loader.clj:60)
	at triple.loader$do_loading.invoke(loader.clj:59)
	at triple.loader$_main.invokeStatic(loader.clj:168)
	at triple.loader$_main.doInvoke(loader.clj:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at triple.loader.main(Unknown Source)

```
