### ISSUE TITLE
Broken transaction in during large loading

### ISSUE THREAD

**Issue by jgrzebyta** [jgrzebyta/triple-loader#24]
Session transaction broken during long session.

Error:
```
20:11.348 [main] ERROR rdf4j.loader -- Initialise error [org.eclipse.rdf4j.repository.RepositoryException]: java.lang.IllegalStateException: Transaction URL has not been set
Exception in thread "main" org.eclipse.rdf4j.repository.RepositoryException: java.lang.IllegalStateException: Transaction URL has not been set
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.rollback(HTTPRepositoryConnection.java:360)
	at rdf4j.loader$fn__634.invokeStatic(loader.clj:93)
	at rdf4j.loader$fn__634.doInvoke(loader.clj:84)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.lang.MultiFn.invoke(MultiFn.java:260)
	at rdf4j.loader$fn__630.invokeStatic(loader.clj:82)
	at rdf4j.loader$fn__630.doInvoke(loader.clj:82)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.lang.MultiFn.invoke(MultiFn.java:260)
	at rdf4j.loader$load_multidata.invokeStatic(loader.clj:147)
	at rdf4j.loader$load_multidata.doInvoke(loader.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at rdf4j.loader$do_loading.invokeStatic(loader.clj:72)
	at rdf4j.loader$do_loading.invoke(loader.clj:63)
	at rdf4j.loader$_main.invokeStatic(loader.clj:172)
	at rdf4j.loader$_main.doInvoke(loader.clj:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at rdf4j.loader.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Transaction URL has not been set
	at org.eclipse.rdf4j.http.client.SesameSession.rollbackTransaction(SesameSession.java:547)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.rollback(HTTPRepositoryConnection.java:353)
	... 17 more
```

Ref #23

**Comment by jgrzebyta** [comment]
Fix in 01a09dd7f76f1f286cefbf4780fb7bcd6dfe1d3c

**Comment by jgrzebyta** [comment]
Error occurs with bigger files (~33M, format RDF/XML).

**Comment by jgrzebyta** [comment]
There problem occurs when *-s* option is not given and default value should be used.
