### ISSUE TITLE
Tavis CI permission deny

### ISSUE THREAD

**Issue by jgrzebyta** [jgrzebyta/triple-loader#5]
I have following error:

```
travis_fold:end:dpl.3
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize': Permission denied - ./target/triple-loader-standalone.jar (Errno::EACCES)
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `new'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `upload_asset'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:130:in `upload_file'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:111:in `block in push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:102:in `each'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:102:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider.rb:143:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider.rb:143:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by jgrzebyta** [comment]
- Upadate `ruby` and `gems` packaging for deploying
- fixed in commit 25fba62
