### ISSUE TITLE
collections/get-first get-rest cannot be processed in different transactions

### ISSUE THREAD

**Issue by jgrzebyta** [jgrzebyta/triple-loader#53]
Stacktrace

```
1240  [ole-0-0] WARN o.e.r.s.m.MemoryStoreConnection: Forced closing of unclosed iteration that was created in: 
java.lang.Throwable: null
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.registerIteration(AbstractSailConnection.java:798)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.getStatements(AbstractSailConnection.java:325)
	at org.eclipse.rdf4j.sail.model.SailModel.iterator(SailModel.java:224)
	at org.eclipse.rdf4j.sail.model.SailModel.access$000(SailModel.java:44)
	at org.eclipse.rdf4j.sail.model.SailModel$1.iterator(SailModel.java:190)
	at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821)
	at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at org.eclipse.rdf4j.model.util.Models.object(Models.java:56)
	at rdf4j.collections$get_rest.invokeStatic(collections.clj:100)
	at rdf4j.collections$get_rest.invoke(collections.clj:95)
	at rdf4j.collections$rdf__GT_seq$fn__1424.invoke(collections.clj:72)
	at rdf4j.collections$rdf__GT_seq.invokeStatic(collections.clj:71)
	at rdf4j.collections$rdf__GT_seq.invoke(collections.clj:60)
	at adalab.experiment_result$nodes_getter.invokeStatic(experiment_result.clj:33)
	at adalab.experiment_result$nodes_getter.invoke(experiment_result.clj:31)
	at adalab.experiment_result$process_data_by_condition_set$iter__2048__2052$fn__2053$fn__2094$fn__2102.invoke(experiment_result.clj:136)
	at adalab.experiment_result$process_data_by_condition_set$iter__2048__2052$fn__2053$fn__2094.invoke(experiment_result.clj:129)
	at adalab.experiment_result$process_data_by_condition_set$fn__2046.invoke(experiment_result.clj:122)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at com.climate.claypoole$pmap_core$start_task__1040$fn__1041.invoke(claypoole.clj:323)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at com.climate.claypoole.impl$binding_conveyor_fn$fn__900.invoke(impl.clj:46)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jgrzebyta** [comment]
Not fixed

**Comment by jgrzebyta** [comment]
Not fixed.

write rdf->seq for `SailRepository`
